# Target-Event-Agent Package: Advanced Functions & Analytics Guide

In addition to extracting Subject-Verb-Object (SVO) triples from text and visualizing them as graphs, the **Target-Event-Agent** package provides several utility functions for merging DataFrames, filtering triples, exporting specific nodes (Subjects, Verbs, Objects), and computing degree centrality metrics.

This guide offers a deeper look into these advanced functions and analytical tools of this library.

By the end of this tutorial, you'll understand how these functions work and how to integrate them into your own Target-Event-Agent workflow.

**First of all, we need to import the modules whodiwhat and teanets.analytics to be able to use them in the scripts.**

In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))
# First of all, we need to import the modules whodiwhat and teanets.analytics to be able to use them in the scripts.
import teanets as tea
import teanets.analytics as wdw_analytics

In [2]:

text = """Gale and Karlach go to a nice pub to drink a tasty beer and a bad wine. 
They love to share stories with each other. 
Wyll really loves eggplants and fantastic aubergines."""

# Extract the SVO triples
df = tea.extract_svos_from_text(text)

[nltk_data] Downloading package wordnet to /home/seb/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

In [3]:
display(df.head())

,Node 1,TEA,Node 2,WDW2,Hypergraph,Semantic-Syntactic,svo_id
0,gale,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
1,karlach,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
2,go,Did,to nice pub,What,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
3,gale,Who,karlach,Who,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
4,gale,Who,drink,Did,"[[('gale', []), ('karlach', [])], ['drink'], [...",0,1

In [4]:
text2 = """Marco and Michelle go to the hawaii to drink a tasty beer and a bad wine."""

# Extract the SVO (subject - verb - object) triples
df2 = tea.extract_svos_from_text(text)
display(df2.head())

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

,Node 1,TEA,Node 2,WDW2,Hypergraph,Semantic-Syntactic,svo_id
0,gale,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
1,karlach,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
2,go,Did,to nice pub,What,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
3,gale,Who,karlach,Who,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
4,gale,Who,drink,Did,"[[('gale', []), ('karlach', [])], ['drink'], [...",0,1

-----

## TEA Manipulation tools

### 1. Merging Multiple TEA DataFrames

**Function**: `merge_svo_dataframes(df_list)`

**Purpose**: Merges a list of DataFrames containing TEA data into a single DataFrame. The function ensures unique `svo_id` values across all merged DataFrames.

In [5]:
df_list = [df, df2]

# Merge them
merged_df = wdw_analytics.merge_svo_dataframes(df_list)

# Display the merged DataFrame
display(merged_df.head())

,Node 1,TEA,Node 2,WDW2,Hypergraph,Semantic-Syntactic,svo_id
0,gale,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
1,karlach,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
2,go,Did,to nice pub,What,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
3,gale,Who,karlach,Who,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
4,gale,Who,drink,Did,"[[('gale', []), ('karlach', [])], ['drink'], [...",0,1

### 2. Saving the TEA data to a CSV file.

The TEA data is saved as as a Pandas dataframe, as such, the pandas function `to_csv` can be used to save the data to a CSV file.

We refer the reader to the pandas documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

### 3. Exporting Elements from the TEA Dataframe


#### Exporting Hypergraphs

**Function**: `export_hypergraphs(df)`

**Purpose**: Extracts syntactic hypergraphs from the DataFrame.

In [6]:
hypergraphs_list = wdw_analytics.export_hypergraphs(df)

print("Number of hypergraphs extracted:", len(hypergraphs_list))
print("Sample hypergraph:", hypergraphs_list[0] if hypergraphs_list else None)

Number of hypergraphs extracted: 4
Sample hypergraph: [[('gale', []), ('karlach', [])], ['go'], [('to nice pub', [])]]

#### Exporting Subjects


**Function**: `export_subj(df)`

**Purpose**: Extracts a set of **unique subjects** from the DataFrame. Each element in the set is a tuple of the form `(subject, valence)`, where `valence` can be `'positive'`, `'negative'`, or `'neutral'`, determined by VADER sentiment.

In [7]:
subjects = wdw_analytics.export_subj(df)
print(subjects)

{('gale', 'neutral'), ('wyll', 'neutral'), ('karlach', 'neutral')}

#### Exporting Objects

**Function**: `export_obj(df)`

**Purpose**: Extracts a set of **unique objects** from the DataFrame. Each element in the set is a tuple of the form `(object, valence)`.

In [8]:
objects = wdw_analytics.export_obj(df)
print(objects)

{('story', 'neutral'), ('eggplant', 'neutral'), ('tasty beer', 'neutral'), ('to nice pub', 'positive'), ('bad wine', 'negative'), ('fantastic aubergine', 'positive')}

#### Exporting Verbs


**Function**: `export_verb(df)`

**Purpose**: Extracts a set of **unique verbs** from the DataFrame. Each element in the set is a tuple of the form `(verb, valence)`.

In [9]:
verbs = wdw_analytics.export_verb(df)
print(verbs)

{('go', 'neutral'), ('love share', 'positive'), ('really love', 'positive'), ('drink', 'neutral')}

### 4. Filtering the SVO DataFrame by TEA

**Function**: `filter_svo_dataframe_by_tea(df, TEA, TEA2=None)`

**Purpose**: Filters the SVO DataFrame to keep rows where `TEA` and `TEA2` match the provided arguments (`"Agent"`, `"Event"`, `"Target"`).  
- If `TEA2` is `None`, it filters by `TEA` alone.  
- Ensures we only look at **syntactic** relationships (`Semantic-Syntactic == 0`).

In [10]:
# Filter to keep only Subject ("Agent") - Verb ("Event") edges
filtered_df_who_did = wdw_analytics.filter_svo_dataframe_by_tea(df, "Agent", "Event")

# Examine the result
display(filtered_df_who_did.head(10))

,Node 1,TEA,Node 2,WDW2,Hypergraph,Semantic-Syntactic,svo_id
0,gale,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
1,karlach,Who,go,Did,"[[('gale', []), ('karlach', [])], ['go'], [('t...",0,0
4,gale,Who,drink,Did,"[[('gale', []), ('karlach', [])], ['drink'], [...",0,1
5,karlach,Who,drink,Did,"[[('gale', []), ('karlach', [])], ['drink'], [...",0,1
10,gale,Who,love share,Did,"[[('gale', []), ('karlach', [])], ['love share...",0,2
11,karlach,Who,love share,Did,"[[('gale', []), ('karlach', [])], ['love share...",0,2
14,wyll,Who,really love,Did,"[[('wyll', [])], ['really love'], [('eggplant'...",0,3

-----

# TEA Analysis tools

Target-Event-Agent (TEA) Networks can be analyzed with standard network science procedures. This library provides convenient functions for filtering, transforming, and analyzing these networks.

## Building Graphs from SVO Data

This library uses NetworkX to build graphs from SVO (Subject-Verb-Object) data. These graphs can then be analyzed with network science. Nodes are labeled with the underlying text (e.g., "gale", "drink", "tasty beer") and typed by their syntactic role ("Agent", "Event", or "Target"). Edges are weighted based on syntactic relations.



**Function**: `svo_to_graph(df, subject_filter=None, object_filter=None)`

**Purpose**  
Convert a DataFrame of SVO data into a NetworkX graph. Optionally filter by specific subjects or objects.  
- Nodes represent subjects, verbs, and objects (with unique IDs like `gale_s` for "gale" and "_s" as a subject).  
- Edges capture relationships:  
  - `relation` is a set of relationship types (`"syntactic"`, `"synonym"`).  
  - `weight` increments for each syntactic occurrence.  
  - `hypergraph` can group edges into higher-level scenarios or sets.

**Parameters**  
- `df` (`pandas.DataFrame`): A TEA Pandas Dataframe.
- `subject_filter` (`function`|`list`|`None`): Filters rows by subject label.  
- `object_filter` (`function`|`list`|`None`): Filters rows by object label.

**Returns**  
- A `networkx.Graph` where each node has:  
  - `label`: Original text (e.g., `"gale"`)  
  - `node_type`: `"subject"`, `"verb"`, or `"object"`  
- Each edge stores:  
  - `relation`: A set of relation types  
  - `hypergraph`: A set of the hypergraphs this node appears in.  
  - `weight`: Integer count of syntactic relations.

In [11]:

G = wdw_analytics.svo_to_graph(df, subject_filter="gale")

# Now you have a networkx Graph G. Nodes and edges contain detailed attributes.
for node in G.nodes(data=True):
    print(node)
for edge in G.edges(data=True):
    print(edge)

('gale_s', {'type': {'subject'}, 'label': 'gale'})
('go_v', {'type': {'verb'}, 'label': 'go'})
('karlach_s', {'type': {'subject'}, 'label': 'karlach'})
('to nice pub_o', {'type': {'object'}, 'label': 'to nice pub'})
('drink_v', {'type': {'verb'}, 'label': 'drink'})
('tasty beer_o', {'type': {'object'}, 'label': 'tasty beer'})
('bad wine_o', {'type': {'object'}, 'label': 'bad wine'})
('love share_v', {'type': {'verb'}, 'label': 'love share'})
('story_o', {'type': {'object'}, 'label': 'story'})
('gale_s', 'go_v', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['go'], [('to nice pub', [])]]"}, 'weight': 1})
('gale_s', 'karlach_s', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['drink'], [('tasty beer', []), ('bad wine', [])]]", "[[('gale', []), ('karlach', [])], ['love share'], [('story', [])]]", "[[('gale', []), ('karlach', [])], ['go'], [('to nice pub', [])]]"}, 'weight': 3})
('gale_s', 'drink_v', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['drink'], [('tasty beer', []), ('bad wine', [])]]"}, 'weight': 1})
('gale_s', 'love share_v', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['love share'], [('story', [])]]"}, 'weight': 1})
('go_v', 'karlach_s', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['go'], [('to nice pub', [])]]"}, 'weight': 1})
('go_v', 'to nice pub_o', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['go'], [('to nice pub', [])]]"}, 'weight': 1})
('karlach_s', 'drink_v', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['drink'], [('tasty beer', []), ('bad wine', [])]]"}, 'weight': 1})
('karlach_s', 'love share_v', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['love share'], [('story', [])]]"}, 'weight': 1})
('drink_v', 'tasty beer_o', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['drink'], [('tasty beer', []), ('bad wine', [])]]"}, 'weight': 1})
('drink_v', 'bad wine_o', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['drink'], [('tasty beer', []), ('bad wine', [])]]"}, 'weight': 1})
('tasty beer_o', 'bad wine_o', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['drink'], [('tasty beer', []), ('bad wine', [])]]"}, 'weight': 1})
('love share_v', 'story_o', {'relation': {'syntactic'}, 'hypergraph': {"[[('gale', []), ('karlach', [])], ['love share'], [('story', [])]]"}, 'weight': 1})


##  Degree Centrality

In network analysis, degree centrality typically measures the number of edges connected to a node. However, in weighted networks, a node’s weighted degree centrality (also sometimes called “node strength”) is the sum of the weights of its edges. This provides a more nuanced view of a node’s importance than simple degree count.

 

### Weighted Degree Centrality


**Function**: `wdw_weighted_degree_centrality(df, TEA, TEA2=None)`

**Purpose**: 
1. Filters the DataFrame according to `TEA` (and optionally `TEA2`).
2. Builds a graph where edges have a weight for each syntactic relationship.
3. Calculates the normalized node strength (sum of edge weights) as the degree centrality.

In [12]:

# Degree centrality for Subjects ("Agent")
subject_centrality_df = wdw_analytics.wdw_weighted_degree_centrality(df, "Agent")
display(subject_centrality_df)

      node  degree_centrality
0     gale               0.30
1  karlach               0.30
2     wyll               0.05

In [13]:
# Degree centrality for Verbs ("Event")
verb_centrality_df = wdw_analytics.wdw_weighted_degree_centrality(df, "Event", None)
display(verb_centrality_df)

          node  degree_centrality
0        drink           0.153846
1           go           0.115385
2   love share           0.115385
3  really love           0.115385

### Weighted Degree Centrality Overview

**Function**: `wdw_degree_centrality_overview(df)`

**Purpose**: A convenient function that prints an **overview** of the top 20 nodes in each role (Subject, Verb, Object) by their **weighted degree centrality**.

In [14]:
wdw_analytics.wdw_degree_centrality_overview(df)

Degree centrality for Subject

      node  degree_centrality
0     gale           0.214286
1  karlach           0.214286
2     wyll           0.071429

############################################

Degree centrality for Verb

          node  degree_centrality
0        drink           0.153846
1           go           0.115385
2   love share           0.115385
3  really love           0.115385

############################################

Degree centrality for Object

                  node  degree_centrality
0          to nice pub           0.083333
1           tasty beer           0.083333
2             bad wine           0.083333
3                story           0.083333
4             eggplant           0.083333
5  fantastic aubergine           0.083333

############################################

-----

# Putting It All Together

Below is a short example workflow illustrating how you might use these functions in tandem:

In [15]:
import teanets as tea
import teanets.analytics as wdw_analytics

# 1. Extract SVOs from multiple texts
text1 = "Gale loves Karlach. They drink coffee together."
text2 = "Wyll meets Gale. They go to a tavern."
df1 = tea.extract_svos_from_text(text1)
df2 = tea.extract_svos_from_text(text2)

# 2. Merge DataFrames
merged_df = wdw_analytics.merge_svo_dataframes([df1, df2])

# 3. Export unique subjects, objects, and verbs
subjects = wdw_analytics.export_subj(merged_df)
objects = wdw_analytics.export_obj(merged_df)
verbs = wdw_analytics.export_verb(merged_df)

# 4. Filter the merged DataFrame to only subject-verb relationships
df_who_did = wdw_analytics.filter_svo_dataframe_by_tea(merged_df, "Agent", "Event")

# 5. Compute Weighted Degree Centrality for subjects
subject_centrality = wdw_analytics.wdw_weighted_degree_centrality(merged_df, "Agent")
print("Subject Weighted Degree Centrality\n", subject_centrality)

# 6. Get an overview of Weighted Degree Centralities (Subject, Verb, Object)
wdw_analytics.wdw_degree_centrality_overview(merged_df)

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Subject Weighted Degree Centrality
    node  degree_centrality
0  they              0.250
1  gale              0.125
2  wyll              0.125
Degree centrality for Subject

   node  degree_centrality
0  they              0.250
1  gale              0.125
2  wyll              0.125

############################################

Degree centrality for Verb

             node  degree_centrality
0            love              0.125
1  drink together              0.125
2            meet              0.125
3              go              0.125

############################################

Degree centrality for Object

        node  degree_centrality
0    karlach              0.125
1     coffee              0.125
2       gale              0.125
3  to tavern              0.125

############################################

-----

# Troubleshooting and Tips

1. **Large Texts**: Processing very large texts might be slow due to dependency parsing and coreference resolution. Consider splitting text into smaller chunks.
2. **Coreference Models**: Ensure you have the correct models downloaded if using `stanza` or `fastcoref`. Consider that `stanza` takes up a significant amount of time and computational power compared to the default `fastcoref`.
3. **Inspecting DataFrames**: Always check intermediate DataFrames (e.g., `df.head()`) to ensure expected behavior.
4. **Synonym vs. Syntactic Relationships**:  
   - `Semantic-Syntactic = 1` indicates a semantic (synonym) relationship (e.g., "eggplant" ~ "aubergine").  
   - `Semantic-Syntactic = 0` indicates a syntactic Target-Event-Agent relationship.


**Enjoy exploring your text data with the Target-Event-Agent package!**